### ISSUE TITLE
If a net has no transitions, will throw exception

### ISSUE THREAD

**Issue by jbush001** [jbush001/WaveView#11]
```
Exception in thread "AWT-EventQueue-0" java.util.NoSuchElementException
	at waveview.TransitionVector$TransitionVectorIterator.next(TransitionVector.java:93)
	at waveview.TransitionVector$TransitionVectorIterator.next(TransitionVector.java:75)
	at waveview.NetNameList$NetNameRenderer.paintComponent(NetNameList.java:99)
```

It assumes there is at least one transition.

```java
            Transition t = fTraceDataModel.findTransition(netId,
                           fTraceDisplayModel.getCursorPosition()).next();
            g.drawString(fTraceDisplayModel.getValueFormatter(fCurrentNet).format(t),
                         1, fValueBaseline);
```

**Comment by jbush001** [comment]
I only caused this with a VCD file I hand created. Most simulators will put at least one transition to set the initial state.
